project_id = "csizkmiplkjyawbscrlx"

[functions.generate-marketing]
verify_jwt = false

[functions.enrich-zillow]
verify_jwt = false

[functions.enrich-airroi]
verify_jwt = false

[functions.verify-address]
verify_jwt = false

[functions.verify-address-batch]
verify_jwt = false

[functions.capture-street-view]
verify_jwt = false

[functions.create-team-member]
verify_jwt = false
