project_id = "csizkmiplkjyawbscrlx"

[functions.batch-update-contact-names]
verify_jwt = false

[functions.update-team-member]
verify_jwt = false

[functions.generate-marketing]
verify_jwt = false

[functions.enrich-zillow]
verify_jwt = false

[functions.enrich-airroi]
verify_jwt = false

[functions.verify-address]
verify_jwt = false

[functions.verify-address-batch]
verify_jwt = false

[functions.capture-street-view]
verify_jwt = false

[functions.create-team-member]
verify_jwt = false

[functions.postalytics-webhook]
verify_jwt = false

[functions.gmail-oauth-callback]
verify_jwt = false

[functions.gmail-sync]
verify_jwt = false

[functions.gmail-webhook]
verify_jwt = false

[functions.gmail-watch]
verify_jwt = false
